name: Generate Documentation

on:
  push:
    branches:
      - main  # Ejecutar este workflow en cada push a la rama principal

jobs:
  build-docs:
    runs-on: ubuntu-22.04

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuración del entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      # Paso 3: Instalación de dependencias de Sphinx
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      # Paso 4: Generar la documentación
      - name: Build Documentation
        run: |
          cd docs
          make html

      # Paso 5: Publicar los archivos generados como artefactos (opcional)
      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html/
